// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VoiceAssistant.Infrastructure;

#nullable disable

namespace CrudWebApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260403215930_AddShopsAndShoppingItemsAndShopProducts")]
    partial class AddShopsAndShoppingItemsAndShopProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VoiceAssistant.Domain.Models.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("website_url");

                    b.HasKey("Id")
                        .HasName("pk_shops");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_shops_created_at");

                    b.ToTable("shops", (string)null);
                });

            modelBuilder.Entity("VoiceAssistant.Domain.Models.ShopProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("description");

                    b.Property<string>("FullProductName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_product_name");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("ShopId")
                        .HasColumnType("uuid")
                        .HasColumnName("shop_id");

                    b.Property<Guid>("ShoppingItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("shopping_item_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_shop_products");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_shop_products_created_at");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_shop_products_shop_id");

                    b.HasIndex("ShoppingItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_shop_products_shopping_item_id");

                    b.ToTable("shop_products", (string)null);
                });

            modelBuilder.Entity("VoiceAssistant.Domain.Models.ShoppingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_shopping_items");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_shopping_items_created_at");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_shopping_items_name");

                    b.ToTable("shopping_items", (string)null);
                });

            modelBuilder.Entity("VoiceAssistant.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_users_created_at");

                    b.HasIndex("EmailAddress")
                        .HasDatabaseName("ix_users_email_address");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_users_status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("VoiceAssistant.Domain.Models.ShopProduct", b =>
                {
                    b.HasOne("VoiceAssistant.Domain.Models.Shop", "Shop")
                        .WithMany("ShopProducts")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_shop_products_shops_shop_id");

                    b.HasOne("VoiceAssistant.Domain.Models.ShoppingItem", "ShoppingItem")
                        .WithOne("ShopProduct")
                        .HasForeignKey("VoiceAssistant.Domain.Models.ShopProduct", "ShoppingItemId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_shop_products_shopping_items_shopping_item_id");

                    b.OwnsOne("VoiceAssistant.Domain.ValueObjects.Amount", "AmountPerItem", b1 =>
                        {
                            b1.Property<Guid>("ShopProductId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("amount_per_item_unit");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric")
                                .HasColumnName("amount_per_item_value");

                            b1.HasKey("ShopProductId");

                            b1.ToTable("shop_products");

                            b1.WithOwner()
                                .HasForeignKey("ShopProductId")
                                .HasConstraintName("fk_shop_products_shop_products_id");
                        });

                    b.Navigation("AmountPerItem");

                    b.Navigation("Shop");

                    b.Navigation("ShoppingItem");
                });

            modelBuilder.Entity("VoiceAssistant.Domain.Models.Shop", b =>
                {
                    b.Navigation("ShopProducts");
                });

            modelBuilder.Entity("VoiceAssistant.Domain.Models.ShoppingItem", b =>
                {
                    b.Navigation("ShopProduct");
                });
#pragma warning restore 612, 618
        }
    }
}
