<Project>

    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>

    <ItemGroup>
        <!-- Entity Framework Core -->
        <PackageVersion Include="EFCore.NamingConventions" Version="10.0.1" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.5" />
        <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.5" />
        <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />

        <!-- ASP.NET Core -->
        <PackageVersion Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.5" />
        <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />

        <!-- Microsoft Extensions -->
        <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.5" />
        <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.5" />
        <PackageVersion Include="Microsoft.Extensions.Options.DataAnnotations" Version="10.0.5" />

        <!-- Serialization -->
        <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />

        <!-- Serilog -->
        <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
        <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />

        <!-- Swagger -->
        <PackageVersion Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    </ItemGroup>

</Project>
